{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "healthcare-nmt.serviceAccountName" . }}
  labels:
    {{- include "healthcare-nmt.labels" . | nindent 4 }}
{{- end }}
