apiVersion: v1
kind: Service
metadata:
  name: {{ include "healthcare-nmt.fullname" . }}
  labels:
    {{- include "healthcare-nmt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "healthcare-nmt.selectorLabels" . | nindent 4 }}
