replicaCount: 1

image:
  repository: 2024aa05086/healthcare-nmt
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []   # e.g. ["dockerhub-secret"]

serviceAccount:
  create: true
  name: ""          # if empty, chart generates name

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 7860
  targetPort: 7860

resources: {}

# Enable if you have an endpoint for health checks
probes:
  enabled: false
  path: "/"
  initialDelaySeconds: 15
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: healthcare-nmt.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
